version: "3.8"

services:
  
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      DB_HOST: ${}DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - curacloud_net

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - curacloud_net

networks:
  curacloud_net:
    driver: bridge